### PR TITLE
Bug fix add new resource

### LINKED ISSUE #149: [Bug] Fix - Add a new resource dialogue on practice page
**Describe the bug**
- In  "Add New Resources " dialogue, form is not following "required" behavior.
- After clicking on "Add new Link" button, it is not checking the values in textfield.
- Accepting blank form.  This can cause the enclosing Practice page to render as blank.

**Expected behavior**
- Follow required field action in "Add New Resources " dialogue.
- needs Validation that all three fields on dialogue are non-null:  Link Type, URL, and Description.
Notes:
- Follow issue #28

### PR DESCRIPTION
**Pull request by piyushsn**
Resolves #149 
- added validations for inputs

### CODE REVIEW

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 1]
```diff
@@ -61,19 +62,43 @@ const useStyles = makeStyles((theme) => ({
...
+
 export default function ResourceAddLink(props) {
   const classes = useStyles();
-
   const [updatePracticeResources] = useMutation(UPDATE_PRACTICE_RESOURCES);
-
-
   const [open, setOpen] = React.useState(false);
   const [linkType, setLinkType] = React.useState('');
+  const [urlValid, setURLValid] = React.useState(true);
```
Comment (jameshbarton) [inline src/components/practicePage/PageBody/ResourceAddLink.js:71]: I recommend making property and setter have consistent naming:  use setUrlValid instead of setURLValid

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 2]
```diff
@@ -61,19 +62,43 @@ const useStyles = makeStyles((theme) => ({
...
+    setURLValid(res);
+  };
+
+  const isValidText = () => {
+    if (!refLinkDesc.current.value) {
+      setTextValid(false);
+      return;
+    }
+    setTextValid(true);
+  };
```
Comment (jameshbarton) [inline src/components/practicePage/PageBody/ResourceAddLink.js:89]: Instead of just testing for non-null input, do we also want to add something like a bad-words check here?
https://www.npmjs.com/package/bad-words

Comment (piyushsn) [reply src/components/practicePage/PageBody/ResourceAddLink.js:89]: Yeah, good idea ..
But do we need to stop an user by adding bad-words ? or
After submission, don't show bad-words?

Comment (shaheinm) [reply src/components/practicePage/PageBody/ResourceAddLink.js:89]: Use the `isProfane` check to set the error state on the link description

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 3]
```diff
@@ -61,19 +62,43 @@ const useStyles = makeStyles((theme) => ({
...
+  const [urlValid, setURLValid] = React.useState(true);
+  const [textValid, setTextValid] = React.useState(false);
   const refLinkUrl = React.useRef();
   const refLinkDesc = React.useRef();
-  const [thankYouOpen, setThankYouOpen] = React.useState(false);
+  const [thankYouOpen, setThankYouOpen] = React.useState(false);  
+
+  const isURLValid = () => {
+    const res = isValidURL(refLinkUrl.current.value);
+    console.log(res);
```
Comment (shaheinm) [inline src/components/practicePage/PageBody/ResourceAddLink.js:79]: no console.log

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 4]
```diff
@@ -61,19 +62,43 @@ const useStyles = makeStyles((theme) => ({
...
+
+  const handleSubmit = async (e) => {
+    e.preventDefault();
+
+    if (!refLinkUrl.current.value || !urlValid) {
+      return;
+    }
 
-  const handleSubmit = async () => {
+    if (!refLinkDesc.current.value) {
```
Comment (shaheinm) [inline src/components/practicePage/PageBody/ResourceAddLink.js:98]: this should also check `!textValid`

Comment (shaheinm) [reply src/components/practicePage/PageBody/ResourceAddLink.js:98]: After you add the `isProfane` check, it'll matter

File: package.json [hunk 5]
```diff
@@ -13,11 +13,13 @@
     "@testing-library/user-event": "^7.1.2",
     "apollo-boost": "^0.4.9",
     "apollo-upload-client": "^13.0.0",
+    "bad-words": "^3.0.3",
     "draft-js": "^0.10.5",
     "draftail": "^1.3.0",
     "graphql": "^15.0.0",
     "markdown-draft-js": "^2.2.0",
     "moment": "^2.25.3",
+    "profanease": "^1.1.2",
```
Comment (shaheinm) [inline package.json:22]: `npm uninstall --save profanease`

File: src/components/practicePage/PageBody/ResourceAddLink.js (hunk 2 above)
Comment (piyushsn) [reply src/components/practicePage/PageBody/ResourceAddLink.js]: done ... :)

File: src/components/practicePage/PageBody/ResourceAddLink.js (hunk 4 above)
Comment (piyushsn) [reply src/components/practicePage/PageBody/ResourceAddLink.js]: done :)

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 6]
```diff
@@ -61,19 +64,44 @@ const useStyles = makeStyles((theme) => ({
...
+    const res = isValidURL(refLinkUrl.current.value);
+    setUrlValid(res);
+  };
+
+  const isValidText = () => {
+    const filter = new Filter();
+    const hasBadWords = filter.isProfane(refLinkDesc.current.value);
+    if (!refLinkDesc.current.value && hasBadWords) {
+      setTextValid(false);
+      return;
```
Comment (shaheinm) [inline src/components/practicePage/PageBody/ResourceAddLink.js:89]: We should probably add tooltips here but I'm okay with ignoring it for now

Comment (shaheinm) [reply src/components/practicePage/PageBody/ResourceAddLink.js:89]: @jameshbarton @lallmon @haithamshahin333 What do you all think? Should we add a tooltip to the invalid url or description fields to let the user know why it's being rejected?

Comment (shaheinm) [reply src/components/practicePage/PageBody/ResourceAddLink.js:89]: @piyushsn If we decide to do it, I'll show you how

File: src/components/practicePage/PageBody/ResourceAddLink.js [hunk 7]
```diff
@@ -61,19 +64,44 @@ const useStyles = makeStyles((theme) => ({
...
+
+  const isURLValid = () => {
+    const res = isValidURL(refLinkUrl.current.value);
+    setUrlValid(res);
+  };
+
+  const isValidText = () => {
+    const filter = new Filter();
+    const hasBadWords = filter.isProfane(refLinkDesc.current.value);
+    if (!refLinkDesc.current.value && hasBadWords) {
```
Comment (shaheinm) [inline src/components/practicePage/PageBody/ResourceAddLink.js:87]: This should be an or operator, not and (`||` not `&&`)

File: src/components/practicePage/PageBody/ResourceAddLink.js (hunk 6 above)
Comment (piyushsn) [reply src/components/practicePage/PageBody/ResourceAddLink.js:89]: sure :)

File: src/components/practicePage/PageBody/ResourceAddLink.js (hunk 7 above)
Comment (piyushsn) [reply src/components/practicePage/PageBody/ResourceAddLink.js:87]: ah, thanks for pointing it out :)

File: src/components/practicePage/PageBody/ResourceAddLink.js (hunk 6 above)
Comment (jameshbarton) [reply src/components/practicePage/PageBody/ResourceAddLink.js:87]: Yes, it would be better to provide a tooltip or some kind of feedback to the user rather than silently munging their content.  Agreed that we could defer this past MVP.

**Review by shaheinm — APPROVED** [review]
